### ISSUE TITLE
Is this project open for contributions?

### ISSUE THREAD

**Issue by edosssa** [brpeanut/eyetracking#1]
Hello! This project seems quite interesting and was wondering if it is open for contribution. A brief overview of what the project id all about would be much appreciated. Cheers!

**Comment by bresheske** [comment]
@king-kay 
I would argue that all open source projects are open for contribution, but I suppose that doesn't mean the author would accept pull requests.  Nothing hurts a fork.  

I'm not really actively researching this any more, as my master's degree is all done, but if you want to dig into it please feel free! It's a windows form's app that contains many implementations for common computer vision algorithms.  Most of them are configurable by pressing space after one is added to the 'applied' list.  You can add multiple filters in different orders, and they are applied in sequence and the final image is displayed on the screen.  

It's not perfect, and is somewhat crude, but it gets its job done for testing and research.
